version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y git

  pre_build:
    commands:
      - echo Setting up the environment...
      - export GITHUB_REPOSITORY="rahul-m21/test-folder" # Repository containing the input folder
      - echo Cloning the target repository...
      - git clone https://github.com/$GITHUB_REPOSITORY target-repo
      - echo Target repository cloned successfully
      - echo Listing the contents of the target repository:
      - ls -R target-repo # Lists all files and folders recursively in the target repository

  build:
    commands:
      - echo Running the PQC Assessment Tool...
      - git clone https://github.com/rahul-m21/Test_Tool.git tool-repo # Clone the runner tool
      - cd tool-repo/PQC_CICD
      - echo Listing the input folder passed to the tool:
      - ls -R ../target-repo # Confirm the input folder content passed to the tool
      - echo Running the PQC Assessment command...
      - ./PQC_Assessment_CICD --inputFolder ../target-repo --outputFolder ./output-folder --database .database/encrypted_data.bin
      - echo Listing the output folder to verify results:
      - ls -R ./output-folder # List all files generated by the tool in the output folder
      - echo PQC Assessment completed successfully

artifacts:
  files:
    - "tool-repo/PQC_CICD/output-folder/**/*" # Collects the output of the tool

env:
  variables:
    GITHUB_REPOSITORY: "rahul-m21/test-folder" # Input folder GitHub repository
