version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y git curl zstd

  pre_build:
    commands:
      - echo Setting up the environment...
      - export GITHUB_REPOSITORY="rahul-m21/test-folder"
      - echo Cloning the target repository...
      - git clone https://github.com/$GITHUB_REPOSITORY target-repo
      - echo Target repository cloned successfully
      - echo Listing the contents of the target repository
      - ls -R target-repo

  build:
    commands:
      - echo Running the PQC Assessment Tool...
      - git clone https://github.com/harinivas-appviewx/Test_Tool.git tool-repo
      - echo Listing the input folder passed to the tool
      - ls -R ./target-repo
      - echo Running the PQC Assessment command...
      - ./tool-repo/PQC_CICD/PQC_Assessment_CICD --inputFolder ./target-repo --outputFolder ./output-folder --configPath ./tool-repo/PQC_CICD/config.ini
      - echo Listing the output folder to verify results
      - ls -R ./output-folder
      - echo PQC Assessment completed successfully

      # Download and extract CodeQL bundle
      - echo Downloading CodeQL bundle...
      - wget https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.20.0/codeql-bundle-linux64.tar.zst --no-check-certificate
      - echo Extracting CodeQL bundle...
      - tar -xvf codeql-bundle-linux64.tar.zst

      # Upload results.sarif to GitHub code scanning
      - echo Uploading SARIF results to GitHub Security Code Scanning...
      - export SARIF_FILE="./output-folder/results.sarif"
      - export GITHUB_URL="https://github.com"
      - export REPO="rahul-m21/test-folder"
      - export COMMIT_SHA=$(git -C target-repo rev-parse HEAD)
      - export REF="refs/heads/main"
      - echo "Commit SHA- $COMMIT_SHA"
      - echo "$GITHUB_TOKEN" | ./codeql/codeql github upload-results --sarif=$SARIF_FILE --github-url=https://github.com/rahul-m21 --repository=$REPO --commit=$COMMIT_SHA --ref=$REF

artifacts:
  files:
    - "./output-folder/**/*"

env:
  variables:
    GITHUB_REPOSITORY: "rahul-m21/test-folder"
